export const ALLOWED_DOMAINS = [
    'damro.lk',
    'singersl.com',
    'strong.lk',
    'singhagiri.lk',
    'ugreen.lk',
    'mysoftlogic.lk',
    'raesl.lk',
    'nanotek.lk',
    'lifemobile.lk',
    'fireworks.lk',
    'simplytek.lk',
    'agc.lk',
    'redlinetech.lk',
];
